# Generated by Django 3.2.4 on 2021-11-11 16:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import kapshop.core.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='DATE UPDATED')),
                ('time_updated', models.TimeField(blank=True, null=True, verbose_name='TIME UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('publish', models.DateField(blank=True, null=True)),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='TOKEN')),
                ('code', models.CharField(default=kapshop.core.utils.coup_randcode_gen, max_length=100, verbose_name='CODE')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='TITLE')),
                ('reason', models.CharField(blank=True, max_length=250, null=True, verbose_name='REASON')),
                ('amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='AMOUNT')),
                ('percent', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='PERCENT')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='DATE FROM')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='DATE TO')),
                ('bool_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='IS ACTIVE')),
            ],
            options={
                'verbose_name_plural': 'coupons',
                'db_table': 'coupons',
            },
        ),
    ]
