# Generated by Django 3.2.4 on 2021-11-11 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import kapshop.core.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='DATE UPDATED')),
                ('time_updated', models.TimeField(blank=True, null=True, verbose_name='TIME UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('publish', models.DateField(blank=True, null=True)),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='TOKEN')),
                ('code', models.CharField(default=kapshop.core.utils.randcode_gen, max_length=100, verbose_name='CODE')),
                ('street_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='STREET NAME')),
                ('apartment_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='HOME NUMBER')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='COUNTRY CODE')),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='POSTAL')),
                ('address_type', models.CharField(blank=True, choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1, null=True, verbose_name='ADDRESS TYPE')),
                ('payment_option', models.CharField(blank=True, max_length=100, null=True, verbose_name='PAYMENT OPTION')),
                ('default', models.BooleanField(blank=True, default=False, null=True, verbose_name='DEFAULT ADDRESS')),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='DATE UPDATED')),
                ('time_updated', models.TimeField(blank=True, null=True, verbose_name='TIME UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('publish', models.DateField(blank=True, null=True)),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('code', models.CharField(default=kapshop.core.utils.shipping_randcode_gen, max_length=100, verbose_name='CODE')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='ADDRESS')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='CITY')),
                ('state', models.CharField(blank=True, max_length=250, null=True, verbose_name='STATE')),
                ('zipcode', models.CharField(blank=True, max_length=250, null=True, verbose_name='ZIP CODE')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='DATE TIME')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USER')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
