# Generated by Django 3.2.4 on 2021-11-11 16:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import kapshop.core.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='DATE UPDATED')),
                ('time_updated', models.TimeField(blank=True, null=True, verbose_name='TIME UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('publish', models.DateField(blank=True, null=True)),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='TOKEN')),
                ('code', models.CharField(default=kapshop.core.utils.pay_randcode_gen, max_length=100, verbose_name='CODE')),
                ('mpesa_charge_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='MPESA PAY ID')),
                ('paypal_charge_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='PAYPAL PAY ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='STRIPE PAY ID')),
                ('amount_paid', models.DecimalField(decimal_places=5, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='AMOUNT PAID')),
                ('amount_outstanding', models.DecimalField(decimal_places=5, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='OUTSTANDING AMOUNT')),
                ('payment_type', models.CharField(blank=True, choices=[(1, 'Mobile Money'), (2, 'Credit Card'), (3, 'Debit Card'), (4, 'Bank Transfer'), (5, 'Paypal'), (6, 'Skrill')], max_length=1, null=True, verbose_name='PAYMENT TYPE')),
                ('card_type', models.CharField(blank=True, choices=[(1, 'Visa'), (2, 'Mastercard'), (3, 'Maestro'), (4, 'American Express'), (5, 'Dinner Club')], max_length=1, null=True, verbose_name='CARD TYPE')),
                ('mob_money_type', models.CharField(blank=True, choices=[(1, 'M-pesa'), (2, 'Orange Money'), (3, 'Airtel Money'), (4, 'Afri Money')], max_length=1, null=True, verbose_name='MOBILE MONEY TYPE')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='banks.bank')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='locations.location')),
            ],
            options={
                'verbose_name_plural': 'payments',
                'db_table': 'payments',
            },
        ),
    ]
