# Generated by Django 3.2.4 on 2021-11-11 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import kapshop.common.upload_images
import kapshop.core.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('sizes', '0001_initial'),
        ('colors', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='DATE UPDATED')),
                ('time_updated', models.TimeField(blank=True, null=True, verbose_name='TIME UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('publish', models.DateField(blank=True, null=True)),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('qty_stock', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='FULL STOCK')),
                ('qty_sold', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='QUANTITY SOLD')),
                ('qty_color', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='QUANTITY BY COLOR')),
                ('qty_size', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='QUANTITY BY SIZE')),
                ('bool_in_stock', models.BooleanField(default=True, verbose_name='IS IN STOCK')),
                ('bool_on_sale', models.BooleanField(default=False, verbose_name='IS ON SALE')),
                ('bool_new', models.BooleanField(default=True, verbose_name='IS NEW')),
                ('bool_baby', models.BooleanField(blank=True, null=True, verbose_name='FOR BABY')),
                ('bool_child', models.BooleanField(blank=True, null=True, verbose_name='FOR CHILD')),
                ('bool_adult', models.BooleanField(blank=True, null=True, verbose_name='FOR ADULT')),
                ('bool_teen', models.BooleanField(blank=True, null=True, verbose_name='FOR TEEN')),
                ('bool_female', models.BooleanField(blank=True, null=True, verbose_name='IS FEMALE PRODUCT')),
                ('bool_male', models.BooleanField(blank=True, null=True, verbose_name='IS MALE PRODUCT')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=kapshop.core.utils.product_randcode_gen, max_length=100, verbose_name='CODE')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='SLUG')),
                ('title', models.CharField(max_length=120, verbose_name='TITLE')),
                ('image', models.ImageField(blank=True, null=True, upload_to=kapshop.common.upload_images.upload_img_path, verbose_name='IMAGE')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, verbose_name='PRICE')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, verbose_name='DISCOUNTED PRICE')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='DESCRIPTION')),
                ('label', models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('danger', 'danger')], max_length=50, null=True, verbose_name='LABEL')),
                ('badge', models.CharField(blank=True, choices=[('Sale', 'Sale'), ('New', 'New'), ('Sold Out', 'Sold Out')], max_length=250, null=True, verbose_name='BADGE NEWS')),
                ('digital', models.BooleanField(blank=True, default=False, null=True, verbose_name='DIGITAL')),
                ('top_featured', models.BooleanField(blank=True, default=False, null=True, verbose_name='TOP FEATURE')),
                ('best_seller', models.BooleanField(blank=True, default=False, null=True, verbose_name='BEST SELLER')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_categories', to='categories.category')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='colors.color')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='sizes.size')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='stores.store')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_subcategories', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'products',
                'db_table': 'Product',
            },
        ),
    ]
